name: Quality check
on:
  push:
    branches:
      - 'master'
      - 'ci'

jobs:
  datree:
    name: Validate Helm charts
    runs-on: 'ubuntu-latest'
    container:
      image: dtzar/helm-kubectl:3.6.3
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./helm

      - name: Install Datree
        run: |
          helm plugin install https://github.com/datreeio/helm-datree

      - name: Datree test
        env:
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
        run: |
          helm datree test ./helm/app -- --values ./helm/kanban-app.yaml

